apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: node-web-app
        version: {{ .Values.app.version }}
    spec:
      containers:
        - name: node-web-app
          image: harbor.lcc3108.ga/library/web-node-app:{{ .Values.app.version }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: node-web-app-config
          ports:
            - containerPort: {{ .Values.app.port }}
