apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: { { .Values.nodeWebApp.replicas } }
  template:
    metadata:
      labels:
        app: node-web-app
        version: { { .Values.nodeWebApp.version } }
    spec:
      containers:
        - name: node-web-app
          image: harbor.lcc3108.ga/library/web-node-app:{{ .Values.nodeWebApp.version }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: node-web-app-config
          ports:
            - containerPort: { { .Values.nodeWebApp.port } }
