apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  namespace: node-web-project
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.node-web-app.port }}
  selector:
    app: node-web-app