apiVersion: v1
kind: ConfigMap
metadata:
  name: node-web-app-config
data:
  VERSION: { { .Values.nodeWebApp.version } }
  HOST: { { .Values.nodeWebApp.host } }
  PORT: { { .Values.nodeWebApp.port } }
