apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  namespace: node-web-project
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-web-app
        version: 1.1.9
    spec:
      containers:
        - name: node-web-app
          image: harbor.lcc3108.ga/library/web-node-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: node-web-app-config
          ports:
            - containerPort: 8080
